networks:
  shared_net:
    driver: bridge

services:

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver_container
    ports:
      - "8978:8978"
    volumes:
      - ./workspace/cloudbeaver-workspace:/opt/cloudbeaver/workspace
    restart: unless-stopped
    environment:
      CLOUDBEAVER_ADMIN_NAME: admin
      CLOUDBEAVER_ADMIN_PASSWORD: Admin123
    networks:
      - shared_net

  postgres:
    build:
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: 
      - ./postgres/postgres.config  
    volumes:
      - ./workspace/postgres:/var/lib/postgresql
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shared_net